/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-05-22 12:35:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.admin.property;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;

public final class report_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    Integer totalCount = (Integer) request.getAttribute("totalCount");
    if (totalCount == null) totalCount = 0;
    Integer paidCount = (Integer) request.getAttribute("paidCount");
    if (paidCount == null) paidCount = 0;
    Integer unpaidCount = (Integer) request.getAttribute("unpaidCount");
    if (unpaidCount == null) unpaidCount = 0;
    Integer appealCount = (Integer) request.getAttribute("appealCount");
    if (appealCount == null) appealCount = 0;
    Integer overdueCount = (Integer) request.getAttribute("overdueCount");
    if (overdueCount == null) overdueCount = 0;
    Double totalAmount = (Double) request.getAttribute("totalAmount");
    if (totalAmount == null) totalAmount = 0.0;
    Double paidAmount = (Double) request.getAttribute("paidAmount");
    if (paidAmount == null) paidAmount = 0.0;
    Double paymentRate = (Double) request.getAttribute("paymentRate");
    if (paymentRate == null) paymentRate = 0.0;
    
    List<Map<String, Object>> monthlyStats = (List<Map<String, Object>>) request.getAttribute("monthlyStats");
    if (monthlyStats == null) monthlyStats = new java.util.ArrayList<>();
    
    String startMonth = (String) request.getAttribute("startMonth");
    if (startMonth == null) startMonth = "";
    String endMonth = (String) request.getAttribute("endMonth");
    if (endMonth == null) endMonth = "";

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>统计报表 - 小区物业管理系统</title>\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- 顶部栏 -->\n");
      out.write("    <div class=\"top-bar\">\n");
      out.write("        <h4>小区物业管理系统</h4>\n");
      out.write("        <div>当前用户：");
      out.print( session.getAttribute("currentUser") != null ? session.getAttribute("currentUser") : "管理员" );
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- 主容器 -->\n");
      out.write("    <div class=\"main-container\">\n");
      out.write("        <!-- 侧边栏 -->\n");
      out.write("        <div class=\"sidebar\">\n");
      out.write("            <div class=\"sidebar-title\">管理菜单</div>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/staff?action=list\" class=\"sidebar-item\">工作人员管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/resident?action=list\" class=\"sidebar-item\">住户管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property?action=list\" class=\"sidebar-item active\">物业费管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/water?action=list\" class=\"sidebar-item\">水费管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/parking?action=list\" class=\"sidebar-item\">车位费管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/repair?action=list\" class=\"sidebar-item\">维修管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/ad?action=list\" class=\"sidebar-item\">广告管理</a>\n");
      out.write("            <div class=\"sidebar-divider\"></div>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"sidebar-item\">退出登录</a>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- 内容区 -->\n");
      out.write("        <div class=\"content-area\">\n");
      out.write("            <!-- 内部导航 -->\n");
      out.write("            <div class=\"property-nav\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property?action=list\">物业费明细</a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/standard?action=list\">收费标准</a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/batch?action=add\">生成账单</a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/appeal?action=list\">申诉管理</a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/report?action=list\" class=\"active\">统计报表</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- 页面标题 -->\n");
      out.write("            <h2 class=\"page-title\">物业费统计报表</h2>\n");
      out.write("            \n");
      out.write("            <!-- 筛选表单 -->\n");
      out.write("            <div class=\"card mb-3\">\n");
      out.write("                <form method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/report\" class=\"d-flex gap-12 align-items-end flex-wrap\">\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"list\">\n");
      out.write("                    <div class=\"form-group\" style=\"margin-bottom:0\">\n");
      out.write("                        <label class=\"form-label\">开始月份</label>\n");
      out.write("                        <input type=\"month\" name=\"startMonth\" class=\"form-control\" value=\"");
      out.print( startMonth );
      out.write("\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\" style=\"margin-bottom:0\">\n");
      out.write("                        <label class=\"form-label\">结束月份</label>\n");
      out.write("                        <input type=\"month\" name=\"endMonth\" class=\"form-control\" value=\"");
      out.print( endMonth );
      out.write("\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\" style=\"margin-bottom:0\">\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary btn-sm\">查询</button>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/report?action=list\" class=\"btn btn-secondary btn-sm\">重置</a>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- 统计卡片 -->\n");
      out.write("            <div class=\"row mb-3\">\n");
      out.write("                <div class=\"col-md-3\">\n");
      out.write("                    <div class=\"card\" style=\"text-align:center;padding:20px\">\n");
      out.write("                        <div style=\"font-size:32px;font-weight:bold;color:var(--primary)\">");
      out.print( totalCount );
      out.write("</div>\n");
      out.write("                        <div style=\"color:var(--text-secondary)\">总账单数</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3\">\n");
      out.write("                    <div class=\"card\" style=\"text-align:center;padding:20px\">\n");
      out.write("                        <div style=\"font-size:32px;font-weight:bold;color:#198754\">");
      out.print( paidCount );
      out.write("</div>\n");
      out.write("                        <div style=\"color:var(--text-secondary)\">已缴费数</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3\">\n");
      out.write("                    <div class=\"card\" style=\"text-align:center;padding:20px\">\n");
      out.write("                        <div style=\"font-size:32px;font-weight:bold;color:#dc3545\">");
      out.print( unpaidCount + overdueCount );
      out.write("</div>\n");
      out.write("                        <div style=\"color:var(--text-secondary)\">未缴费数</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3\">\n");
      out.write("                    <div class=\"card\" style=\"text-align:center;padding:20px\">\n");
      out.write("                        <div style=\"font-size:32px;font-weight:bold;color:var(--primary)\">");
      out.print( String.format("%.1f", paymentRate) );
      out.write("%</div>\n");
      out.write("                        <div style=\"color:var(--text-secondary)\">收缴率</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- 金额统计 + 饼图 -->\n");
      out.write("            <div class=\"row mb-3\">\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"card\" style=\"padding:20px\">\n");
      out.write("                        <h5 style=\"margin-bottom:16px\">费用统计</h5>\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\" style=\"border-bottom:1px solid var(--border);padding-bottom:8px\">\n");
      out.write("                            <span>应缴总额</span>\n");
      out.write("                            <span style=\"font-weight:bold\">¥");
      out.print( String.format("%.2f", totalAmount) );
      out.write("</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\" style=\"border-bottom:1px solid var(--border);padding-bottom:8px\">\n");
      out.write("                            <span>实缴总额</span>\n");
      out.write("                            <span style=\"font-weight:bold;color:#198754\">¥");
      out.print( String.format("%.2f", paidAmount) );
      out.write("</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"d-flex justify-content-between\">\n");
      out.write("                            <span>待缴总额</span>\n");
      out.write("                            <span style=\"font-weight:bold;color:#dc3545\">¥");
      out.print( String.format("%.2f", totalAmount - paidAmount) );
      out.write("</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-8\">\n");
      out.write("                    <div class=\"card\" style=\"padding:20px\">\n");
      out.write("                        <h5 style=\"margin-bottom:16px\">收缴状态分布</h5>\n");
      out.write("                        <canvas id=\"paymentChart\" width=\"400\" height=\"200\"></canvas>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- 月度汇总表格 -->\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h5 style=\"padding:12px 16px;border-bottom:1px solid var(--border);margin:0\">月度汇总</h5>\n");
      out.write("                <table class=\"table-custom\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>月份</th>\n");
      out.write("                            <th>总账单数</th>\n");
      out.write("                            <th>已缴数</th>\n");
      out.write("                            <th>未缴数</th>\n");
      out.write("                            <th>申诉中</th>\n");
      out.write("                            <th>应缴金额</th>\n");
      out.write("                            <th>实缴金额</th>\n");
      out.write("                            <th>收缴率</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        ");

                        if (monthlyStats.isEmpty()) {
                        
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td colspan=\"8\" class=\"text-center\" style=\"color:var(--text-secondary);padding:40px\">\n");
      out.write("                                暂无数据\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        ");

                        } else {
                            for (Map<String, Object> stats : monthlyStats) {
                        
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>");
      out.print( stats.get("billMonth") != null ? stats.get("billMonth") : "" );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( stats.get("totalCount") != null ? stats.get("totalCount") : 0 );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( stats.get("paidCount") != null ? stats.get("paidCount") : 0 );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( stats.get("unpaidCount") != null ? stats.get("unpaidCount") : 0 );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( stats.get("appealCount") != null ? stats.get("appealCount") : 0 );
      out.write("</td>\n");
      out.write("                            <td>¥");
      out.print( stats.get("totalAmount") != null ? String.format("%.2f", stats.get("totalAmount")) : "0.00" );
      out.write("</td>\n");
      out.write("                            <td>¥");
      out.print( stats.get("paidAmount") != null ? String.format("%.2f", stats.get("paidAmount")) : "0.00" );
      out.write("</td>\n");
      out.write("                            <td>\n");
      out.write("                                ");

                                    double rate = 0;
                                    if (stats.get("paymentRate") != null) {
                                        rate = ((Number) stats.get("paymentRate")).doubleValue();
                                    }
                                    String rateColor = rate >= 80 ? "#198754" : rate >= 50 ? "#ffc107" : "#dc3545";
                                
      out.write("\n");
      out.write("                                <span style=\"color:");
      out.print( rateColor );
      out.write(";font-weight:bold\">");
      out.print( String.format("%.1f", rate) );
      out.write("%</span>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        ");

                            }
                        
      out.write("\n");
      out.write("                        <tr style=\"background:#f5f5f5;font-weight:bold\">\n");
      out.write("                            <td>合计</td>\n");
      out.write("                            <td>");
      out.print( totalCount );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( paidCount );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( unpaidCount + overdueCount );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( appealCount );
      out.write("</td>\n");
      out.write("                            <td>¥");
      out.print( String.format("%.2f", totalAmount) );
      out.write("</td>\n");
      out.write("                            <td>¥");
      out.print( String.format("%.2f", paidAmount) );
      out.write("</td>\n");
      out.write("                            <td><span style=\"color:");
      out.print( paymentRate >= 80 ? "#198754" : paymentRate >= 50 ? "#ffc107" : "#dc3545" );
      out.write('"');
      out.write('>');
      out.print( String.format("%.1f", paymentRate) );
      out.write("%</span></td>\n");
      out.write("                        </tr>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("    // 收缴状态饼图\n");
      out.write("    const ctx = document.getElementById('paymentChart').getContext('2d');\n");
      out.write("    new Chart(ctx, {\n");
      out.write("        type: 'doughnut',\n");
      out.write("        data: {\n");
      out.write("            labels: ['已缴', '未缴', '申诉中', '逾期'],\n");
      out.write("            datasets: [{\n");
      out.write("                data: [");
      out.print( paidCount );
      out.write(',');
      out.write(' ');
      out.print( unpaidCount );
      out.write(',');
      out.write(' ');
      out.print( appealCount );
      out.write(',');
      out.write(' ');
      out.print( overdueCount );
      out.write("],\n");
      out.write("                backgroundColor: ['#198754', '#dc3545', '#ffc107', '#fd7e14'],\n");
      out.write("                borderWidth: 0\n");
      out.write("            }]\n");
      out.write("        },\n");
      out.write("        options: {\n");
      out.write("            responsive: true,\n");
      out.write("            plugins: {\n");
      out.write("                legend: {\n");
      out.write("                    position: 'right',\n");
      out.write("                    labels: {\n");
      out.write("                        padding: 20,\n");
      out.write("                        usePointStyle: true\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".property-nav {\n");
      out.write("    display: flex;\n");
      out.write("    gap: 4px;\n");
      out.write("    margin-bottom: 16px;\n");
      out.write("    border-bottom: 1px solid var(--border);\n");
      out.write("    padding-bottom: 12px;\n");
      out.write("}\n");
      out.write(".property-nav a {\n");
      out.write("    padding: 8px 16px;\n");
      out.write("    color: var(--text-secondary);\n");
      out.write("    text-decoration: none;\n");
      out.write("    border-radius: var(--radius-btn);\n");
      out.write("    font-size: 14px;\n");
      out.write("    transition: all 0.2s;\n");
      out.write("}\n");
      out.write(".property-nav a:hover {\n");
      out.write("    background-color: var(--bg-page);\n");
      out.write("    color: var(--primary);\n");
      out.write("}\n");
      out.write(".property-nav a.active {\n");
      out.write("    background-color: var(--primary);\n");
      out.write("    color: white;\n");
      out.write("}\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
