/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-05-22 12:37:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.admin.property;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.property.model.PropertyStandard;

public final class standard_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.property.model.PropertyStandard");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    List<PropertyStandard> list = (List<PropertyStandard>) request.getAttribute("list");
    if (list == null) list = new java.util.ArrayList<>();

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>收费标准管理 - 小区物业管理系统</title>\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- 顶部栏 -->\n");
      out.write("    <div class=\"top-bar\">\n");
      out.write("        <h4>小区物业管理系统</h4>\n");
      out.write("        <div>当前用户：");
      out.print( session.getAttribute("currentUser") != null ? session.getAttribute("currentUser") : "管理员" );
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- 主容器 -->\n");
      out.write("    <div class=\"main-container\">\n");
      out.write("        <!-- 侧边栏 -->\n");
      out.write("        <div class=\"sidebar\">\n");
      out.write("            <div class=\"sidebar-title\">管理菜单</div>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/staff?action=list\" class=\"sidebar-item\">工作人员管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/resident?action=list\" class=\"sidebar-item\">住户管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property?action=list\" class=\"sidebar-item active\">物业费管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/water?action=list\" class=\"sidebar-item\">水费管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/parking?action=list\" class=\"sidebar-item\">车位费管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/repair?action=list\" class=\"sidebar-item\">维修管理</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/ad?action=list\" class=\"sidebar-item\">广告管理</a>\n");
      out.write("            <div class=\"sidebar-divider\"></div>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"sidebar-item\">退出登录</a>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- 内容区 -->\n");
      out.write("        <div class=\"content-area\">\n");
      out.write("            <!-- 内部导航 -->\n");
      out.write("            <div class=\"property-nav\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property?action=list\">物业费明细</a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/standard?action=list\" class=\"active\">收费标准</a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/batch?action=add\">生成账单</a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/appeal?action=list\">申诉管理</a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/report?action=list\">统计报表</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- 页面标题 & 新增按钮 -->\n");
      out.write("            <div class=\"d-flex justify-content-between align-items-center mb-3\">\n");
      out.write("                <h2 class=\"page-title\" style=\"margin-bottom:0\">收费标准管理</h2>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/standard?action=add\" class=\"btn btn-primary\">新增标准</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- 数据表格 -->\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <table class=\"table-custom\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>标准ID</th>\n");
      out.write("                            <th>收费类型</th>\n");
      out.write("                            <th>单价（元/m²/月）</th>\n");
      out.write("                            <th>生效日期</th>\n");
      out.write("                            <th>状态</th>\n");
      out.write("                            <th>创建时间</th>\n");
      out.write("                            <th>操作</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        ");

                        if (list.isEmpty()) {
                        
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td colspan=\"7\" class=\"text-center\" style=\"color:var(--text-secondary);padding:40px\">\n");
      out.write("                                暂无数据，请点击\"新增标准\"添加\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        ");

                        } else {
                            for (PropertyStandard standard : list) {
                                String statusClass = "生效".equals(standard.getStatus()) ? "status-success" : "status-error";
                        
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>");
      out.print( standard.getStandardId() != null ? standard.getStandardId() : "" );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( standard.getFeeType() != null ? standard.getFeeType() : "" );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( standard.getUnitPrice() != null ? "¥" + standard.getUnitPrice().setScale(2) : "¥0.00" );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( standard.getEffectiveDate() != null ? new java.text.SimpleDateFormat("yyyy-MM-dd").format(standard.getEffectiveDate()) : "" );
      out.write("</td>\n");
      out.write("                            <td><span class=\"status-tag ");
      out.print( statusClass );
      out.write('"');
      out.write('>');
      out.print( standard.getStatus() != null ? standard.getStatus() : "" );
      out.write("</span></td>\n");
      out.write("                            <td>");
      out.print( standard.getCreatedAt() != null ? new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm").format(standard.getCreatedAt()) : "" );
      out.write("</td>\n");
      out.write("                            <td>\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/standard?action=edit&standardId=");
      out.print( standard.getStandardId() );
      out.write("\" \n");
      out.write("                                   class=\"btn btn-secondary btn-sm\">编辑</a>\n");
      out.write("                                ");
 if ("生效".equals(standard.getStatus())) { 
      out.write("\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/standard?action=disable&standardId=");
      out.print( standard.getStandardId() );
      out.write("\" \n");
      out.write("                                   class=\"btn btn-sm\" style=\"background:#FFF3E0;color:#E65100;border:1px solid #E65100\"\n");
      out.write("                                   onclick=\"return confirm('确定停用该标准？')\">停用</a>\n");
      out.write("                                ");
 } else { 
      out.write("\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/standard?action=enable&standardId=");
      out.print( standard.getStandardId() );
      out.write("\" \n");
      out.write("                                   class=\"btn btn-primary btn-sm\"\n");
      out.write("                                   onclick=\"return confirm('确定启用该标准？')\">启用</a>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/property/standard?action=delete&standardId=");
      out.print( standard.getStandardId() );
      out.write("\" \n");
      out.write("                                   class=\"btn btn-sm\" style=\"background:#FFEBEE;color:#C62828;border:1px solid #C62828\"\n");
      out.write("                                   onclick=\"return confirm('确定删除该标准？删除后不可恢复！')\">删除</a>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        ");

                                }
                            }
                        
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".property-nav {\n");
      out.write("    display: flex;\n");
      out.write("    gap: 4px;\n");
      out.write("    margin-bottom: 16px;\n");
      out.write("    border-bottom: 1px solid var(--border);\n");
      out.write("    padding-bottom: 12px;\n");
      out.write("}\n");
      out.write(".property-nav a {\n");
      out.write("    padding: 8px 16px;\n");
      out.write("    color: var(--text-secondary);\n");
      out.write("    text-decoration: none;\n");
      out.write("    border-radius: var(--radius-btn);\n");
      out.write("    font-size: 14px;\n");
      out.write("    transition: all 0.2s;\n");
      out.write("}\n");
      out.write(".property-nav a:hover {\n");
      out.write("    background-color: var(--bg-page);\n");
      out.write("    color: var(--primary);\n");
      out.write("}\n");
      out.write(".property-nav a.active {\n");
      out.write("    background-color: var(--primary);\n");
      out.write("    color: white;\n");
      out.write("}\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
