/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-05-25 10:16:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.admin.parking;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.property.entity.ParkingSpace;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.property.entity.ParkingSpace");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    List<ParkingSpace> list = (List<ParkingSpace>) request.getAttribute("list");
    String sortOrder = (String) request.getAttribute("sortOrder");
    String filterStatus = (String) request.getAttribute("filterStatus");
    String filterLocation = (String) request.getAttribute("filterLocation");
    String filterOverdue = (String) request.getAttribute("filterOverdue");
    if (filterStatus == null) filterStatus = "";
    if (filterLocation == null) filterLocation = "";

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>车位管理</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 0; }\n");
      out.write("        .content-area { flex: 1; padding: 20px; }\n");
      out.write("        .filter-bar { display: flex; gap: 10px; margin-bottom: 15px; flex-wrap: wrap; align-items: center; }\n");
      out.write("        .filter-bar select, .filter-bar input { padding: 5px 10px; border: 1px solid #ccc; border-radius: 4px; }\n");
      out.write("        .filter-bar .btn { cursor: pointer; }\n");
      out.write("        table { width: 100%; border-collapse: collapse; margin-top: 15px; }\n");
      out.write("        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; font-size: 14px; }\n");
      out.write("        th { background-color: #f2f2f2; white-space: nowrap; }\n");
      out.write("        .badge { padding: 3px 10px; border-radius: 4px; color: white; font-size: 12px; }\n");
      out.write("        .badge-success { background-color: #28a745; }\n");
      out.write("        .badge-secondary { background-color: #6c757d; }\n");
      out.write("        .badge-danger { background-color: #dc3545; }\n");
      out.write("        .btn { padding: 5px 12px; text-decoration: none; border-radius: 4px; color: white; font-size: 12px; display: inline-block; }\n");
      out.write("        .btn-info { background-color: #17a2b8; }\n");
      out.write("        .btn-warning { background-color: #ffc107; color: #000; }\n");
      out.write("        .btn-primary { background-color: #007bff; }\n");
      out.write("        .btn-danger { background-color: #dc3545; }\n");
      out.write("        .stats { margin-bottom: 15px; }\n");
      out.write("        .stats span { margin-right: 20px; font-size: 14px; color: #666; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");

    request.setAttribute("module", "parking");

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/pages/common/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"main-container\">\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/pages/common/admin-sidebar.jsp", out, false);
      out.write("\n");
      out.write("    <div class=\"content-area\">\n");
      out.write("        <h2>车位管理</h2>\n");
      out.write("        <div class=\"stats\">\n");
      out.write("            <span>共 <strong>");
      out.print(list != null ? list.size() : 0);
      out.write("</strong> 个车位</span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"filter-bar\">\n");
      out.write("            <span>编号排序：</span>\n");
      out.write("            <select name=\"sortOrder\" onchange=\"applyFilter()\" style=\"width:100px;\">\n");
      out.write("                <option value=\"asc\" ");
      out.print(!"desc".equals(sortOrder) ? "selected" : "");
      out.write(">升序(小→大)</option>\n");
      out.write("                <option value=\"desc\" ");
      out.print("desc".equals(sortOrder) ? "selected" : "");
      out.write(">降序(大→小)</option>\n");
      out.write("            </select>\n");
      out.write("            <span>状态：</span>\n");
      out.write("            <select name=\"status\" onchange=\"applyFilter()\" style=\"width:120px;\">\n");
      out.write("                <option value=\"\">全部</option>\n");
      out.write("                <option value=\"空闲\" ");
      out.print("空闲".equals(filterStatus) ? "selected" : "");
      out.write(">空闲</option>\n");
      out.write("                <option value=\"已绑定\" ");
      out.print("已绑定".equals(filterStatus) ? "selected" : "");
      out.write(">已绑定</option>\n");
      out.write("            </select>\n");
      out.write("            <span>位置：</span>\n");
      out.write("            <select name=\"location\" onchange=\"applyFilter()\" style=\"width:140px;\">\n");
      out.write("                <option value=\"\">全部</option>\n");
      out.write("                <option value=\"地下一层A区\" ");
      out.print("地下一层A区".equals(filterLocation) ? "selected" : "");
      out.write(">地下一层A区</option>\n");
      out.write("                <option value=\"地下一层B区\" ");
      out.print("地下一层B区".equals(filterLocation) ? "selected" : "");
      out.write(">地下一层B区</option>\n");
      out.write("                <option value=\"地下一层C区\" ");
      out.print("地下一层C区".equals(filterLocation) ? "selected" : "");
      out.write(">地下一层C区</option>\n");
      out.write("                <option value=\"户外停车场\" ");
      out.print("户外停车场".equals(filterLocation) ? "selected" : "");
      out.write(">户外停车场</option>\n");
      out.write("            </select>\n");
      out.write("            <label style=\"display:flex; align-items:center; gap:4px; cursor:pointer;\">\n");
      out.write("                <input type=\"checkbox\" name=\"overdue\" value=\"true\" ");
      out.print("true".equals(filterOverdue) ? "checked" : "");
      out.write(" onchange=\"applyFilter()\"> 仅看欠费车位\n");
      out.write("            </label>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/parking?action=standardList\" class=\"btn btn-primary\">设定月费标准</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/parking?action=applyList\" class=\"btn btn-warning\" style=\"margin-left:auto;\">绑定申请列表</a>\n");
      out.write("        </div>\n");
      out.write("        ");
 if (list == null || list.isEmpty()) { 
      out.write("\n");
      out.write("            <p style=\"color:#999;\">暂无匹配的车位数据。</p>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <tr>\n");
      out.write("                <th>车位编号</th><th>位置</th><th>类型</th><th>状态</th><th>绑定住户</th><th>缴费状态</th><th>操作</th>\n");
      out.write("            </tr>\n");
      out.write("            ");
 for (ParkingSpace sp : list) {
                String feeBadge = "badge-secondary";
                if ("欠费".equals(sp.getFeeStatus())) feeBadge = "badge-danger";
                else if ("正常".equals(sp.getFeeStatus())) feeBadge = "badge-success";
            
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <td>");
      out.print(sp.getSpaceNo());
      out.write("</td>\n");
      out.write("                <td>");
      out.print(sp.getLocation());
      out.write("</td>\n");
      out.write("                <td>");
      out.print(sp.getType());
      out.write("</td>\n");
      out.write("                <td><span class=\"badge ");
      out.print( "已绑定".equals(sp.getStatus()) ? "badge-success" : "badge-secondary" );
      out.write('"');
      out.write('>');
      out.print(sp.getStatus());
      out.write("</span></td>\n");
      out.write("                <td>");
      out.print(sp.getResidentName() != null ? sp.getResidentName() : "--");
      out.write("</td>\n");
      out.write("                <td><span class=\"badge ");
      out.print(feeBadge);
      out.write('"');
      out.write('>');
      out.print(sp.getFeeStatus() != null ? sp.getFeeStatus() : "正常");
      out.write("</span></td>\n");
      out.write("                <td>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/parking?action=detail&spaceId=");
      out.print(sp.getSpaceId());
      out.write("\" class=\"btn btn-info\">查看详情</a>\n");
      out.write("                    ");
 if ("已绑定".equals(sp.getStatus())) { 
      out.write("\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/parking?action=unbind&spaceId=");
      out.print(sp.getSpaceId());
      out.write("\" class=\"btn btn-danger\" onclick=\"return confirm('确定要移除该车位的绑定吗？')\">移除绑定</a>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </table>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/pages/common/footer.jsp", out, false);
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("function applyFilter() {\n");
      out.write("    var params = [];\n");
      out.write("    var sort = document.querySelector('[name=sortOrder]').value;\n");
      out.write("    var st = document.querySelector('[name=status]').value;\n");
      out.write("    var loc = document.querySelector('[name=location]').value;\n");
      out.write("    var ov = document.querySelector('[name=overdue]').checked;\n");
      out.write("    params.push('action=list');\n");
      out.write("    params.push('sortOrder=' + sort);\n");
      out.write("    if (st) params.push('status=' + encodeURIComponent(st));\n");
      out.write("    if (loc) params.push('location=' + encodeURIComponent(loc));\n");
      out.write("    if (ov) params.push('overdue=true');\n");
      out.write("    window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/parking?' + params.join('&');\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
