/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-05-25 06:18:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>物业管理系统 - 测试入口</title>\n");
      out.write("    <style>\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\n");
      out.write("        body { font-family: \"Microsoft YaHei\", Arial, sans-serif; background: #f0f2f5; min-height: 100vh; }\n");
      out.write("        .page-header { background: linear-gradient(135deg, #1B5E20, #2E7D32); color: white; padding: 24px; text-align: center; }\n");
      out.write("        .page-header h1 { font-size: 24px; }\n");
      out.write("        .page-header p { font-size: 13px; opacity: 0.85; margin-top: 4px; }\n");
      out.write("        .container { max-width: 1100px; margin: 24px auto; padding: 0 20px; }\n");
      out.write("        .card { background: white; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); margin-bottom: 20px; }\n");
      out.write("        .card-header { padding: 16px 20px; border-bottom: 1px solid #e8e8e8; font-size: 16px; font-weight: bold; color: #333; display: flex; justify-content: space-between; align-items: center; }\n");
      out.write("        .card-body { padding: 20px; }\n");
      out.write("\n");
      out.write("        .btn { padding: 8px 20px; border: none; border-radius: 4px; cursor: pointer; font-size: 14px; display: inline-flex; align-items: center; gap: 6px; }\n");
      out.write("        .btn-primary { background: #2E7D32; color: white; }\n");
      out.write("        .btn-primary:hover { background: #1B5E20; }\n");
      out.write("        .btn-blue { background: #1976D2; color: white; }\n");
      out.write("        .btn-blue:hover { background: #1565C0; }\n");
      out.write("        .btn-orange { background: #FF6F00; color: white; }\n");
      out.write("        .btn-orange:hover { background: #E65100; }\n");
      out.write("        .btn-outline { background: white; color: #2E7D32; border: 1px solid #2E7D32; }\n");
      out.write("        .btn-outline:hover { background: #E8F5E9; }\n");
      out.write("        .btn:disabled { opacity: 0.5; cursor: not-allowed; }\n");
      out.write("\n");
      out.write("        .status-bar { padding: 10px 16px; border-radius: 4px; margin-bottom: 12px; font-size: 13px; display: none; }\n");
      out.write("        .status-success { background: #E8F5E9; color: #2E7D32; border: 1px solid #A5D6A7; }\n");
      out.write("        .status-error { background: #FFEBEE; color: #C62828; border: 1px solid #EF9A9A; }\n");
      out.write("\n");
      out.write("        .form-row { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 12px; }\n");
      out.write("        .form-group { flex: 1; min-width: 160px; }\n");
      out.write("        .form-group label { display: block; font-size: 13px; color: #666; margin-bottom: 4px; }\n");
      out.write("        .form-group input, .form-group select { width: 100%; padding: 8px 12px; border: 1px solid #ddd; border-radius: 4px; font-size: 14px; }\n");
      out.write("        .form-group input:focus, .form-group select:focus { outline: none; border-color: #2E7D32; }\n");
      out.write("\n");
      out.write("        table { width: 100%; border-collapse: collapse; }\n");
      out.write("        th { background: #fafafa; padding: 10px 12px; text-align: left; font-size: 13px; color: #666; border-bottom: 2px solid #e8e8e8; }\n");
      out.write("        td { padding: 10px 12px; border-bottom: 1px solid #f0f0f0; font-size: 14px; }\n");
      out.write("        tr:hover td { background: #f9f9f9; }\n");
      out.write("        .badge { padding: 2px 10px; border-radius: 12px; font-size: 12px; }\n");
      out.write("        .badge-admin { background: #FFF3E0; color: #E65100; }\n");
      out.write("        .badge-owner { background: #E8F5E9; color: #2E7D32; }\n");
      out.write("        .badge-staff { background: #E3F2FD; color: #1565C0; }\n");
      out.write("        .badge-orange { background: #FFF3E0; color: #E65100; }\n");
      out.write("        .login-link { color: #2E7D32; text-decoration: none; font-weight: bold; cursor: pointer; }\n");
      out.write("        .login-link:hover { text-decoration: underline; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"page-header\">\n");
      out.write("    <h1>物业管理系统</h1>\n");
      out.write("    <p>本地测试入口 — 选择账号即可快速登入</p>\n");
      out.write("</div>\n");
      out.write("<div class=\"container\">\n");
      out.write("\n");
      out.write("    ");
 if ("noresident".equals(request.getParameter("error"))) { 
      out.write("\n");
      out.write("    <div style=\"background:#FFF3E0;border:1px solid #FFB74D;color:#E65100;padding:16px 20px;border-radius:6px;margin-bottom:20px;font-size:14px;display:flex;align-items:center;gap:8px;\">\n");
      out.write("        <span style=\"font-size:18px;\">&#9888;</span>\n");
      out.write("        <span>该业主账号尚未绑定住户信息，请先在右上角删除该账号后重新创建，或联系管理员手动绑定 Resident 记录。</span>\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <!-- 1. 数据库联通测试 -->\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <div class=\"card-header\">\n");
      out.write("            数据库连接测试\n");
      out.write("            <button class=\"btn btn-blue\" onclick=\"testDB()\" id=\"btnTestDB\">测试连接</button>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("            <div id=\"dbStatus\" class=\"status-bar\"></div>\n");
      out.write("            <p style=\"font-size:13px;color:#999;\">服务器：LAPTOP-B23PEHD3\\MSSQLSERVER01 &nbsp;|&nbsp; 数据库：PropertyManagementDB</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 2. 新增测试账号 -->\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <div class=\"card-header\">新增测试账号</div>\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("            <div id=\"addStatus\" class=\"status-bar\"></div>\n");
      out.write("\n");
      out.write("            <!-- 基础信息（所有角色必填） -->\n");
      out.write("            <div class=\"form-row\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label>用户名 <span style=\"color:red;\">*</span></label>\n");
      out.write("                    <input type=\"text\" id=\"username\" placeholder=\"登录用户名\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label>密码 <span style=\"color:red;\">*</span></label>\n");
      out.write("                    <input type=\"text\" id=\"password\" value=\"123456\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label>角色 <span style=\"color:red;\">*</span></label>\n");
      out.write("                    <select id=\"userType\" onchange=\"onRoleChange()\">\n");
      out.write("                        <option value=\"业主\">业主</option>\n");
      out.write("                        <option value=\"管理员\">管理员</option>\n");
      out.write("                        <option value=\"维修员\">维修员</option>\n");
      out.write("                        <option value=\"广告公司\">广告公司</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- 详细信息（根据角色动态显示） -->\n");
      out.write("            <div id=\"detailFields\" style=\"border-top:1px dashed #ddd;padding-top:12px;margin-top:4px;\">\n");
      out.write("                <!-- 所有角色通用 -->\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>姓名 <span style=\"color:red;\">*</span></label>\n");
      out.write("                        <input type=\"text\" id=\"detailName\" placeholder=\"真实姓名\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>电话 <span style=\"color:red;\">*</span></label>\n");
      out.write("                        <input type=\"text\" id=\"detailPhone\" placeholder=\"手机号\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>身份证号 <span style=\"color:red;\">*</span></label>\n");
      out.write("                        <input type=\"text\" id=\"detailIdCard\" placeholder=\"18位身份证号\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- 业主专属 -->\n");
      out.write("                <div id=\"ownerFields\">\n");
      out.write("                    <div class=\"form-row\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>入住日期</label>\n");
      out.write("                            <input type=\"date\" id=\"checkInDate\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <p style=\"font-size:13px;color:#666;margin-bottom:8px;font-weight:bold;\">房屋信息</p>\n");
      out.write("                    <div class=\"form-row\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>楼栋 <span style=\"color:red;\">*</span></label>\n");
      out.write("                            <input type=\"text\" id=\"building\" placeholder=\"如：A\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>单元 <span style=\"color:red;\">*</span></label>\n");
      out.write("                            <input type=\"text\" id=\"unit\" placeholder=\"如：1\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>房号 <span style=\"color:red;\">*</span></label>\n");
      out.write("                            <input type=\"text\" id=\"roomNo\" placeholder=\"如：101\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-row\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>面积(m²) <span style=\"color:red;\">*</span></label>\n");
      out.write("                            <input type=\"number\" step=\"0.01\" id=\"area\" placeholder=\"如：89.50\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>楼层 <span style=\"color:red;\">*</span></label>\n");
      out.write("                            <input type=\"number\" id=\"floor\" placeholder=\"如：1\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>户型 <span style=\"color:red;\">*</span></label>\n");
      out.write("                            <select id=\"houseType\">\n");
      out.write("                                <option value=\"\">请选择</option>\n");
      out.write("                                <option value=\"一室一厅\">一室一厅</option>\n");
      out.write("                                <option value=\"两室一厅\">两室一厅</option>\n");
      out.write("                                <option value=\"三室一厅\">三室一厅</option>\n");
      out.write("                                <option value=\"三室两厅\">三室两厅</option>\n");
      out.write("                                <option value=\"四室两厅\">四室两厅</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- 维修员专属 -->\n");
      out.write("                <div class=\"form-row\" id=\"staffFields\" style=\"display:none;\">\n");
      out.write("                    <div class=\"form-group\" style=\"max-width:300px;\">\n");
      out.write("                        <label>工种</label>\n");
      out.write("                        <select id=\"workTypeId\">\n");
      out.write("                            <option value=\"\">加载中...</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- 广告公司专属 -->\n");
      out.write("                <div id=\"companyFields\" style=\"display:none;\">\n");
      out.write("                    <div class=\"form-row\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>公司名称 <span style=\"color:red;\">*</span></label>\n");
      out.write("                            <input type=\"text\" id=\"companyName\" placeholder=\"广告公司全称\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label>联系人 <span style=\"color:red;\">*</span></label>\n");
      out.write("                            <input type=\"text\" id=\"companyContact\" placeholder=\"联系人姓名\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <button class=\"btn btn-primary\" onclick=\"addUser()\">创建账号</button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 3. 选择账号登入 -->\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <div class=\"card-header\">\n");
      out.write("            已有账号列表\n");
      out.write("            <button class=\"btn btn-outline\" onclick=\"loadUsers()\">刷新列表</button>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("            <table>\n");
      out.write("                <thead>\n");
      out.write("                    <tr><th>用户ID</th><th>用户名</th><th>角色</th><th>姓名</th><th>电话</th><th>操作</th></tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody id=\"userTableBody\">\n");
      out.write("                    <tr><td colspan=\"6\" style=\"text-align:center;color:#999;\">点击\"刷新列表\"加载账号数据</td></tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("var ctx = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("var workTypes = [];\n");
      out.write("\n");
      out.write("function showStatus(id, type, msg) {\n");
      out.write("    var el = document.getElementById(id);\n");
      out.write("    el.className = 'status-bar status-' + (type === 'success' ? 'success' : 'error');\n");
      out.write("    el.textContent = msg;\n");
      out.write("    el.style.display = 'block';\n");
      out.write("    setTimeout(function(){ el.style.display = 'none'; }, 5000);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function onRoleChange() {\n");
      out.write("    var role = document.getElementById('userType').value;\n");
      out.write("    var ownerFields = document.getElementById('ownerFields');\n");
      out.write("    var staffFields = document.getElementById('staffFields');\n");
      out.write("    var companyFields = document.getElementById('companyFields');\n");
      out.write("\n");
      out.write("    if (role === '业主') {\n");
      out.write("        ownerFields.style.display = '';\n");
      out.write("        staffFields.style.display = 'none';\n");
      out.write("        companyFields.style.display = 'none';\n");
      out.write("    } else if (role === '维修员') {\n");
      out.write("        ownerFields.style.display = 'none';\n");
      out.write("        staffFields.style.display = '';\n");
      out.write("        companyFields.style.display = 'none';\n");
      out.write("    } else if (role === '广告公司') {\n");
      out.write("        ownerFields.style.display = 'none';\n");
      out.write("        staffFields.style.display = 'none';\n");
      out.write("        companyFields.style.display = '';\n");
      out.write("    } else {\n");
      out.write("        ownerFields.style.display = 'none';\n");
      out.write("        staffFields.style.display = 'none';\n");
      out.write("        companyFields.style.display = 'none';\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function loadWorkTypes() {\n");
      out.write("    fetch(ctx + '/test?action=workTypes')\n");
      out.write("        .then(function(r) { return r.json(); })\n");
      out.write("        .then(function(list) {\n");
      out.write("            workTypes = list;\n");
      out.write("            var sel = document.getElementById('workTypeId');\n");
      out.write("            sel.innerHTML = '';\n");
      out.write("            list.forEach(function(w) {\n");
      out.write("                sel.innerHTML += '<option value=\"' + w.worktypeId + '\">' + w.worktypeName + '</option>';\n");
      out.write("            });\n");
      out.write("        })\n");
      out.write("        .catch(function() {\n");
      out.write("            document.getElementById('workTypeId').innerHTML = '<option value=\"\">加载失败</option>';\n");
      out.write("        });\n");
      out.write("}\n");
      out.write("\n");
      out.write("function testDB() {\n");
      out.write("    var btn = document.getElementById('btnTestDB');\n");
      out.write("    btn.disabled = true;\n");
      out.write("    btn.textContent = '测试中...';\n");
      out.write("    fetch(ctx + '/test?action=db')\n");
      out.write("        .then(function(r) { return r.json(); })\n");
      out.write("        .then(function(data) {\n");
      out.write("            showStatus('dbStatus', data.success ? 'success' : 'error', data.message);\n");
      out.write("            btn.disabled = false;\n");
      out.write("            btn.textContent = '测试连接';\n");
      out.write("        })\n");
      out.write("        .catch(function() {\n");
      out.write("            showStatus('dbStatus', 'error', '请求失败，请检查服务器');\n");
      out.write("            btn.disabled = false;\n");
      out.write("            btn.textContent = '测试连接';\n");
      out.write("        });\n");
      out.write("}\n");
      out.write("\n");
      out.write("function addUser() {\n");
      out.write("    var username = document.getElementById('username').value.trim();\n");
      out.write("    var password = document.getElementById('password').value.trim();\n");
      out.write("    var userType = document.getElementById('userType').value;\n");
      out.write("    var name = document.getElementById('detailName').value.trim();\n");
      out.write("    var phone = document.getElementById('detailPhone').value.trim();\n");
      out.write("    var idCard = document.getElementById('detailIdCard').value.trim();\n");
      out.write("\n");
      out.write("    if (!username) { showStatus('addStatus', 'error', '请输入用户名'); return; }\n");
      out.write("    if (!password) { showStatus('addStatus', 'error', '请输入密码'); return; }\n");
      out.write("    if (!name) { showStatus('addStatus', 'error', '请输入姓名'); return; }\n");
      out.write("    if (!phone) { showStatus('addStatus', 'error', '请输入电话'); return; }\n");
      out.write("    if (!idCard) { showStatus('addStatus', 'error', '请输入身份证号'); return; }\n");
      out.write("    if (idCard.length !== 18) { showStatus('addStatus', 'error', '身份证号必须为18位'); return; }\n");
      out.write("\n");
      out.write("    var params = new URLSearchParams();\n");
      out.write("    params.append('action', 'addUser');\n");
      out.write("    params.append('username', username);\n");
      out.write("    params.append('password', password);\n");
      out.write("    params.append('userType', userType);\n");
      out.write("    params.append('name', name);\n");
      out.write("    params.append('phone', phone);\n");
      out.write("    params.append('idCard', idCard);\n");
      out.write("\n");
      out.write("    if (userType === '业主') {\n");
      out.write("        var checkInDate = document.getElementById('checkInDate').value;\n");
      out.write("        if (!checkInDate) { showStatus('addStatus', 'error', '请选择入住日期'); return; }\n");
      out.write("        var building = document.getElementById('building').value.trim();\n");
      out.write("        var unit = document.getElementById('unit').value.trim();\n");
      out.write("        var roomNo = document.getElementById('roomNo').value.trim();\n");
      out.write("        var area = document.getElementById('area').value.trim();\n");
      out.write("        var ffloor = document.getElementById('floor').value.trim();\n");
      out.write("        var houseType = document.getElementById('houseType').value;\n");
      out.write("        if (!building) { showStatus('addStatus', 'error', '请输入楼栋'); return; }\n");
      out.write("        if (!unit) { showStatus('addStatus', 'error', '请输入单元'); return; }\n");
      out.write("        if (!roomNo) { showStatus('addStatus', 'error', '请输入房号'); return; }\n");
      out.write("        if (!area) { showStatus('addStatus', 'error', '请输入面积'); return; }\n");
      out.write("        if (!ffloor) { showStatus('addStatus', 'error', '请输入楼层'); return; }\n");
      out.write("        if (!houseType) { showStatus('addStatus', 'error', '请选择户型'); return; }\n");
      out.write("        params.append('checkInDate', checkInDate);\n");
      out.write("        params.append('building', building);\n");
      out.write("        params.append('unit', unit);\n");
      out.write("        params.append('roomNo', roomNo);\n");
      out.write("        params.append('area', area);\n");
      out.write("        params.append('floor', ffloor);\n");
      out.write("        params.append('houseType', houseType);\n");
      out.write("    }\n");
      out.write("    if (userType === '维修员') {\n");
      out.write("        var workTypeId = document.getElementById('workTypeId').value;\n");
      out.write("        if (!workTypeId) { showStatus('addStatus', 'error', '请选择工种'); return; }\n");
      out.write("        params.append('workTypeId', workTypeId);\n");
      out.write("    }\n");
      out.write("    if (userType === '广告公司') {\n");
      out.write("        var companyName = document.getElementById('companyName').value.trim();\n");
      out.write("        var companyContact = document.getElementById('companyContact').value.trim();\n");
      out.write("        if (!companyName) { showStatus('addStatus', 'error', '请输入公司名称'); return; }\n");
      out.write("        if (!companyContact) { showStatus('addStatus', 'error', '请输入联系人'); return; }\n");
      out.write("        params.append('companyName', companyName);\n");
      out.write("        params.append('companyContact', companyContact);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    fetch(ctx + '/test?' + params.toString())\n");
      out.write("        .then(function(r) { return r.json(); })\n");
      out.write("        .then(function(data) {\n");
      out.write("            showStatus('addStatus', data.success ? 'success' : 'error', data.message);\n");
      out.write("            if (data.success) {\n");
      out.write("                document.getElementById('username').value = '';\n");
      out.write("                document.getElementById('detailName').value = '';\n");
      out.write("                document.getElementById('detailPhone').value = '';\n");
      out.write("                document.getElementById('detailIdCard').value = '';\n");
      out.write("                document.getElementById('checkInDate').value = '';\n");
      out.write("                document.getElementById('building').value = '';\n");
      out.write("                document.getElementById('unit').value = '';\n");
      out.write("                document.getElementById('roomNo').value = '';\n");
      out.write("                document.getElementById('area').value = '';\n");
      out.write("                document.getElementById('floor').value = '';\n");
      out.write("                document.getElementById('houseType').value = '';\n");
      out.write("                loadUsers();\n");
      out.write("            }\n");
      out.write("        })\n");
      out.write("        .catch(function() {\n");
      out.write("            showStatus('addStatus', 'error', '创建失败，请检查服务');\n");
      out.write("        });\n");
      out.write("}\n");
      out.write("\n");
      out.write("function loadUsers() {\n");
      out.write("    var tbody = document.getElementById('userTableBody');\n");
      out.write("    tbody.innerHTML = '<tr><td colspan=\"6\" style=\"text-align:center;color:#999;\">加载中...</td></tr>';\n");
      out.write("    fetch(ctx + '/test?action=users')\n");
      out.write("        .then(function(r) { return r.json(); })\n");
      out.write("        .then(function(users) {\n");
      out.write("            if (users.length === 0) {\n");
      out.write("                tbody.innerHTML = '<tr><td colspan=\"6\" style=\"text-align:center;color:#999;\">暂无账号，请先新增</td></tr>';\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            var html = '';\n");
      out.write("            var badgeMap = {'管理员': 'badge-admin', '业主': 'badge-owner', '维修员': 'badge-staff', '广告公司': 'badge-orange'};\n");
      out.write("            users.forEach(function(u) {\n");
      out.write("                html += '<tr>';\n");
      out.write("                html += '<td>' + u.userId + '</td>';\n");
      out.write("                html += '<td>' + u.username + '</td>';\n");
      out.write("                html += '<td><span class=\"badge ' + (badgeMap[u.userType] || '') + '\">' + u.userType + '</span></td>';\n");
      out.write("                html += '<td>' + (u.realName || '-') + '</td>';\n");
      out.write("                html += '<td>' + (u.phone || '-') + '</td>';\n");
      out.write("                html += '<td><a class=\"login-link\" href=\"' + ctx + '/login?userId=' + u.userId + '\">进入系统</a></td>';\n");
      out.write("                html += '</tr>';\n");
      out.write("            });\n");
      out.write("            tbody.innerHTML = html;\n");
      out.write("        })\n");
      out.write("        .catch(function() {\n");
      out.write("            tbody.innerHTML = '<tr><td colspan=\"6\" style=\"text-align:center;color:red;\">加载失败，请检查服务</td></tr>';\n");
      out.write("        });\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 页面加载时初始化\n");
      out.write("window.onload = function() {\n");
      out.write("    loadUsers();\n");
      out.write("    loadWorkTypes();\n");
      out.write("    onRoleChange();\n");
      out.write("};\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
