/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-05-25 11:24:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.property.dao.WorkTypeDAO;
import com.property.entity.WorkType;
import java.util.List;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.property.entity.WorkType");
    _jspx_imports_classes.add("com.property.dao.WorkTypeDAO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    String error = (String) request.getAttribute("error");
    if (error == null) error = "";

    // 回显表单数据（注册失败时）
    String reg_username = (String) request.getAttribute("reg_username");
    String reg_userType = (String) request.getAttribute("reg_userType");
    String reg_name = (String) request.getAttribute("reg_name");
    String reg_phone = (String) request.getAttribute("reg_phone");
    String reg_idCard = (String) request.getAttribute("reg_idCard");
    String reg_checkInDate = (String) request.getAttribute("reg_checkInDate");
    String reg_building = (String) request.getAttribute("reg_building");
    String reg_unit = (String) request.getAttribute("reg_unit");
    String reg_roomNo = (String) request.getAttribute("reg_roomNo");
    String reg_area = (String) request.getAttribute("reg_area");
    String reg_floor = (String) request.getAttribute("reg_floor");
    String reg_houseType = (String) request.getAttribute("reg_houseType");
    String reg_workTypeId = (String) request.getAttribute("reg_workTypeId");
    String reg_companyName = (String) request.getAttribute("reg_companyName");

    if (reg_username == null) reg_username = "";
    if (reg_userType == null) reg_userType = "业主";
    if (reg_name == null) reg_name = "";
    if (reg_phone == null) reg_phone = "";
    if (reg_idCard == null) reg_idCard = "";
    if (reg_checkInDate == null) reg_checkInDate = "";
    if (reg_building == null) reg_building = "";
    if (reg_unit == null) reg_unit = "";
    if (reg_roomNo == null) reg_roomNo = "";
    if (reg_area == null) reg_area = "";
    if (reg_floor == null) reg_floor = "";
    if (reg_houseType == null) reg_houseType = "";
    if (reg_workTypeId == null) reg_workTypeId = "";
    if (reg_companyName == null) reg_companyName = "";

    // 加载工种列表
    WorkTypeDAO workTypeDAO = new WorkTypeDAO();
    List<WorkType> workTypes = workTypeDAO.findForStaff();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>物业管理系统 - 注册</title>\n");
      out.write("    <style>\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\n");
      out.write("        body { font-family: \"Microsoft YaHei\", Arial, sans-serif; background: linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%); min-height: 100vh; display: flex; justify-content: center; align-items: center; padding: 20px; }\n");
      out.write("        .register-box { background: white; padding: 36px 40px; border-radius: 8px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); width: 520px; max-width: 100%; }\n");
      out.write("        .register-box h2 { text-align: center; color: #2E7D32; margin-bottom: 6px; font-size: 22px; }\n");
      out.write("        .register-box .subtitle { text-align: center; color: #999; font-size: 13px; margin-bottom: 22px; }\n");
      out.write("        .form-row { display: flex; gap: 12px; margin-bottom: 14px; }\n");
      out.write("        .form-group { flex: 1; min-width: 0; margin-bottom: 14px; }\n");
      out.write("        .form-group label { display: block; margin-bottom: 5px; color: #555; font-size: 13px; }\n");
      out.write("        .form-group label .req { color: red; }\n");
      out.write("        .form-group input, .form-group select { width: 100%; padding: 9px 12px; border: 1px solid #ddd; border-radius: 4px; font-size: 14px; }\n");
      out.write("        .form-group input:focus, .form-group select:focus { outline: none; border-color: #2E7D32; }\n");
      out.write("        .section-title { font-size: 14px; font-weight: bold; color: #333; border-bottom: 1px dashed #ddd; padding-bottom: 6px; margin: 6px 0 12px; }\n");
      out.write("        .btn-register { width: 100%; padding: 12px; background: #2E7D32; color: white; border: none; border-radius: 4px; font-size: 16px; cursor: pointer; transition: background 0.2s; margin-top: 4px; }\n");
      out.write("        .btn-register:hover { background: #1B5E20; }\n");
      out.write("        .error-msg { background: #FFEBEE; color: #C62828; border: 1px solid #EF9A9A; padding: 10px 14px; border-radius: 4px; margin-bottom: 16px; font-size: 13px; text-align: center; }\n");
      out.write("        .links { text-align: center; margin-top: 16px; font-size: 13px; color: #999; }\n");
      out.write("        .links a { color: #2E7D32; text-decoration: none; }\n");
      out.write("        .links a:hover { text-decoration: underline; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"register-box\">\n");
      out.write("        <h2>创建账号</h2>\n");
      out.write("        <p class=\"subtitle\">注册后可登录使用物业管理系统</p>\n");
      out.write("\n");
      out.write("        ");
 if (!error.isEmpty()) { 
      out.write("\n");
      out.write("        <div class=\"error-msg\">");
      out.print( error );
      out.write("</div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" method=\"post\">\n");
      out.write("            <!-- 登录信息 -->\n");
      out.write("            <p class=\"section-title\">登录信息</p>\n");
      out.write("            <div class=\"form-row\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label><span class=\"req\">*</span> 用户名</label>\n");
      out.write("                    <input type=\"text\" name=\"username\" value=\"");
      out.print( reg_username );
      out.write("\" placeholder=\"登录用户名\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label><span class=\"req\">*</span> 角色</label>\n");
      out.write("                    <select name=\"userType\" id=\"userType\" onchange=\"onRoleChange()\">\n");
      out.write("                        <option value=\"业主\" ");
      out.print( "业主".equals(reg_userType) ? "selected" : "" );
      out.write(">业主</option>\n");
      out.write("                        <option value=\"管理员\" ");
      out.print( "管理员".equals(reg_userType) ? "selected" : "" );
      out.write(">管理员</option>\n");
      out.write("                        <option value=\"维修员\" ");
      out.print( "维修员".equals(reg_userType) ? "selected" : "" );
      out.write(">维修员</option>\n");
      out.write("                        <option value=\"广告公司\" ");
      out.print( "广告公司".equals(reg_userType) ? "selected" : "" );
      out.write(">广告公司</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-row\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label><span class=\"req\">*</span> 密码</label>\n");
      out.write("                    <input type=\"password\" name=\"password\" placeholder=\"至少6位\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label><span class=\"req\">*</span> 确认密码</label>\n");
      out.write("                    <input type=\"password\" name=\"confirmPassword\" placeholder=\"再次输入密码\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- 个人信息 -->\n");
      out.write("            <p class=\"section-title\">个人信息</p>\n");
      out.write("            <div class=\"form-row\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label><span class=\"req\">*</span> 姓名</label>\n");
      out.write("                    <input type=\"text\" name=\"name\" value=\"");
      out.print( reg_name );
      out.write("\" placeholder=\"真实姓名\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label><span class=\"req\">*</span> 电话</label>\n");
      out.write("                    <input type=\"text\" name=\"phone\" value=\"");
      out.print( reg_phone );
      out.write("\" placeholder=\"手机号\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label>身份证号</label>\n");
      out.write("                    <input type=\"text\" name=\"idCard\" value=\"");
      out.print( reg_idCard );
      out.write("\" placeholder=\"18位身份证号\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- 业主专属 -->\n");
      out.write("            <div id=\"ownerFields\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label>入住日期</label>\n");
      out.write("                    <input type=\"date\" name=\"checkInDate\" value=\"");
      out.print( reg_checkInDate );
      out.write("\">\n");
      out.write("                </div>\n");
      out.write("                <p class=\"section-title\">房屋信息</p>\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label><span class=\"req\">*</span> 楼栋</label>\n");
      out.write("                        <input type=\"text\" name=\"building\" value=\"");
      out.print( reg_building );
      out.write("\" placeholder=\"如：A\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label><span class=\"req\">*</span> 单元</label>\n");
      out.write("                        <input type=\"text\" name=\"unit\" value=\"");
      out.print( reg_unit );
      out.write("\" placeholder=\"如：1\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label><span class=\"req\">*</span> 房号</label>\n");
      out.write("                        <input type=\"text\" name=\"roomNo\" value=\"");
      out.print( reg_roomNo );
      out.write("\" placeholder=\"如：101\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>面积(m²)</label>\n");
      out.write("                        <input type=\"number\" step=\"0.01\" name=\"area\" value=\"");
      out.print( reg_area );
      out.write("\" placeholder=\"如：89.50\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>楼层</label>\n");
      out.write("                        <input type=\"number\" name=\"floor\" value=\"");
      out.print( reg_floor );
      out.write("\" placeholder=\"如：1\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>户型</label>\n");
      out.write("                        <select name=\"houseType\">\n");
      out.write("                            <option value=\"\">请选择</option>\n");
      out.write("                            <option value=\"一室一厅\" ");
      out.print( "一室一厅".equals(reg_houseType) ? "selected" : "" );
      out.write(">一室一厅</option>\n");
      out.write("                            <option value=\"两室一厅\" ");
      out.print( "两室一厅".equals(reg_houseType) ? "selected" : "" );
      out.write(">两室一厅</option>\n");
      out.write("                            <option value=\"三室一厅\" ");
      out.print( "三室一厅".equals(reg_houseType) ? "selected" : "" );
      out.write(">三室一厅</option>\n");
      out.write("                            <option value=\"三室两厅\" ");
      out.print( "三室两厅".equals(reg_houseType) ? "selected" : "" );
      out.write(">三室两厅</option>\n");
      out.write("                            <option value=\"四室两厅\" ");
      out.print( "四室两厅".equals(reg_houseType) ? "selected" : "" );
      out.write(">四室两厅</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- 维修员专属 -->\n");
      out.write("            <div id=\"staffFields\" style=\"display:none;\">\n");
      out.write("                <div class=\"form-group\" style=\"max-width:300px;\">\n");
      out.write("                    <label><span class=\"req\">*</span> 工种</label>\n");
      out.write("                    <select name=\"workTypeId\">\n");
      out.write("                        ");
 for (WorkType wt : workTypes) { 
      out.write("\n");
      out.write("                        <option value=\"");
      out.print( wt.getWorktypeId() );
      out.write('"');
      out.write(' ');
      out.print( wt.getWorktypeId().equals(reg_workTypeId) ? "selected" : "" );
      out.write('>');
      out.print( wt.getWorktypeName() );
      out.write("</option>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- 广告公司专属 -->\n");
      out.write("            <div id=\"companyFields\" style=\"display:none;\">\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label><span class=\"req\">*</span> 公司名称</label>\n");
      out.write("                        <input type=\"text\" name=\"companyName\" value=\"");
      out.print( reg_companyName );
      out.write("\" placeholder=\"广告公司全称\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <button type=\"submit\" class=\"btn-register\">注 册</button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <div class=\"links\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp\">已有账号？去登录</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("    function onRoleChange() {\n");
      out.write("        var role = document.getElementById('userType').value;\n");
      out.write("        document.getElementById('ownerFields').style.display = (role === '业主') ? '' : 'none';\n");
      out.write("        document.getElementById('staffFields').style.display = (role === '维修员') ? '' : 'none';\n");
      out.write("        document.getElementById('companyFields').style.display = (role === '广告公司') ? '' : 'none';\n");
      out.write("    }\n");
      out.write("    window.onload = function() { onRoleChange(); };\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
