/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-05-22 12:35:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.owner.property;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.property.model.PropertyFeeDetail;

public final class pay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.property.model.PropertyFeeDetail");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    PropertyFeeDetail detail = (PropertyFeeDetail) request.getAttribute("entity");
    if (detail == null) {
        detail = new PropertyFeeDetail();
    }
    String error = (String) request.getAttribute("error");
    if (error == null) error = "";

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>在线支付 - 小区物业管理系统</title>\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- 顶部栏 -->\n");
      out.write("    <div class=\"top-bar\">\n");
      out.write("        <h4>小区物业管理系统</h4>\n");
      out.write("        <div>当前用户：");
      out.print( session.getAttribute("currentUser") != null ? session.getAttribute("currentUser") : "业主" );
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- 主容器 -->\n");
      out.write("    <div class=\"main-container\">\n");
      out.write("        <!-- 侧边栏 -->\n");
      out.write("        <div class=\"sidebar\">\n");
      out.write("            <div class=\"sidebar-title\">业主菜单</div>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/owner/personal?action=info\" class=\"sidebar-item\">个人信息</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/owner/property?action=list\" class=\"sidebar-item active\">物业费</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/owner/water?action=list\" class=\"sidebar-item\">水费</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/owner/repair?action=list\" class=\"sidebar-item\">维修申请</a>\n");
      out.write("            <div class=\"sidebar-divider\"></div>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"sidebar-item\">退出登录</a>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- 内容区 -->\n");
      out.write("        <div class=\"content-area\">\n");
      out.write("            <!-- 内部导航 -->\n");
      out.write("            <div class=\"property-nav\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/owner/property?action=list\">我的账单</a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/owner/property/appeal?action=list\">申诉记录</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- 页面标题 -->\n");
      out.write("            <h2 class=\"page-title\">在线支付</h2>\n");
      out.write("            \n");
      out.write("            <!-- 返回按钮 -->\n");
      out.write("            <div class=\"mb-3\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/owner/property?action=list\" class=\"btn btn-secondary\">\n");
      out.write("                    &larr; 返回列表\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
 if (!error.isEmpty()) { 
      out.write("\n");
      out.write("            <div class=\"card\" style=\"border-left:4px solid var(--error);margin-bottom:16px\">\n");
      out.write("                <p style=\"color:var(--error);margin:0;padding:12px\">");
      out.print( error );
      out.write("</p>\n");
      out.write("            </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            <!-- 费用明细 -->\n");
      out.write("            <div class=\"card mb-3\">\n");
      out.write("                <h5 style=\"padding:12px 16px;border-bottom:1px solid var(--border);margin:0\">应付金额</h5>\n");
      out.write("                <div style=\"padding:24px;text-align:center\">\n");
      out.write("                    <div style=\"font-size:48px;font-weight:bold;color:var(--primary)\">\n");
      out.write("                        ¥");
      out.print( detail.getAmount() != null ? detail.getAmount().setScale(2) : "0.00" );
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div style=\"color:var(--text-secondary);margin-top:8px\">\n");
      out.write("                        ");
      out.print( detail.getBillMonth() != null ? detail.getBillMonth() : "" );
      out.write(" · \n");
      out.write("                        ");
      out.print( detail.getStandardType() != null ? detail.getStandardType() : "物业费" );
      out.write(" · \n");
      out.write("                        ");
      out.print( detail.getHousingAddress() != null ? detail.getHousingAddress() : "" );
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- 支付方式选择 -->\n");
      out.write("            <div class=\"card mb-3\">\n");
      out.write("                <h5 style=\"padding:12px 16px;border-bottom:1px solid var(--border);margin:0\">选择支付方式</h5>\n");
      out.write("                <div style=\"padding:16px\">\n");
      out.write("                    <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/owner/property/pay\">\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"save\">\n");
      out.write("                        <input type=\"hidden\" name=\"detailId\" value=\"");
      out.print( detail.getDetailId() );
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"amount\" value=\"");
      out.print( detail.getAmount() );
      out.write("\">\n");
      out.write("                        \n");
      out.write("                        <div class=\"payment-methods\">\n");
      out.write("                            <label class=\"payment-method\">\n");
      out.write("                                <input type=\"radio\" name=\"paymentMethod\" value=\"微信支付\" required checked>\n");
      out.write("                                <div class=\"payment-method-content\">\n");
      out.write("                                    <div class=\"payment-icon\" style=\"background:#07C160\">\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"white\" width=\"32\" height=\"32\">\n");
      out.write("                                            <path d=\"M8.5 11.5c-.5.5-1 .5-1.5.5-.5 0-1-.2-1.5-.5-.5-.3-.5-1-.5-1.5s0-1.2.5-1.5c.5-.3 1-.5 1.5-.5s1 .2 1.5.5c.5.3.5 1 .5 1.5s-.2 1-.5 1.5z\"/>\n");
      out.write("                                            <path d=\"M15.5 11.5c.5.5 1 .5 1.5.5.5 0 1-.2 1.5-.5.5-.3.5-1 .5-1.5s0-1.2-.5-1.5c-.5-.3-1-.5-1.5-.5s-1 .2-1.5.5c-.5.3-.5 1-.5 1.5s.2 1 .5 1.5z\"/>\n");
      out.write("                                            <path d=\"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8z\"/>\n");
      out.write("                                        </svg>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <div style=\"font-weight:bold\">微信支付</div>\n");
      out.write("                                        <div style=\"font-size:12px;color:var(--text-secondary)\">使用微信支付</div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </label>\n");
      out.write("                            \n");
      out.write("                            <label class=\"payment-method\">\n");
      out.write("                                <input type=\"radio\" name=\"paymentMethod\" value=\"支付宝\">\n");
      out.write("                                <div class=\"payment-method-content\">\n");
      out.write("                                    <div class=\"payment-icon\" style=\"background:#1677FF\">\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"white\" width=\"32\" height=\"32\">\n");
      out.write("                                            <path d=\"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8z\"/>\n");
      out.write("                                            <text x=\"7\" y=\"15\" font-size=\"10\" fill=\"white\">¥</text>\n");
      out.write("                                        </svg>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <div style=\"font-weight:bold\">支付宝</div>\n");
      out.write("                                        <div style=\"font-size:12px;color:var(--text-secondary)\">使用支付宝支付</div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </label>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block mt-3\" onclick=\"return confirm('确认支付 ¥");
      out.print( detail.getAmount() != null ? detail.getAmount().setScale(2) : "0.00" );
      out.write("？')\">\n");
      out.write("                            确认支付\n");
      out.write("                        </button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- 提示 -->\n");
      out.write("            <div class=\"card\" style=\"background:#fff3e0;border-left:4px solid #ff9800\">\n");
      out.write("                <div style=\"padding:12px\">\n");
      out.write("                    <strong>支付说明：</strong>\n");
      out.write("                    <ul style=\"margin-bottom:0;padding-left:20px;margin-top:8px\">\n");
      out.write("                        <li>本系统为模拟支付，无需真实付款</li>\n");
      out.write("                        <li>点击确认支付后，系统将模拟支付成功</li>\n");
      out.write("                        <li>支付成功后可查看电子凭证</li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".property-nav {\n");
      out.write("    display: flex;\n");
      out.write("    gap: 4px;\n");
      out.write("    margin-bottom: 16px;\n");
      out.write("    border-bottom: 1px solid var(--border);\n");
      out.write("    padding-bottom: 12px;\n");
      out.write("}\n");
      out.write(".property-nav a {\n");
      out.write("    padding: 8px 16px;\n");
      out.write("    color: var(--text-secondary);\n");
      out.write("    text-decoration: none;\n");
      out.write("    border-radius: var(--radius-btn);\n");
      out.write("    font-size: 14px;\n");
      out.write("    transition: all 0.2s;\n");
      out.write("}\n");
      out.write(".property-nav a:hover {\n");
      out.write("    background-color: var(--bg-page);\n");
      out.write("    color: var(--primary);\n");
      out.write("}\n");
      out.write(".property-nav a.active {\n");
      out.write("    background-color: var(--primary);\n");
      out.write("    color: white;\n");
      out.write("}\n");
      out.write(".payment-methods {\n");
      out.write("    display: flex;\n");
      out.write("    gap: 12px;\n");
      out.write("}\n");
      out.write(".payment-method {\n");
      out.write("    flex: 1;\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write(".payment-method input[type=\"radio\"] {\n");
      out.write("    display: none;\n");
      out.write("}\n");
      out.write(".payment-method-content {\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    gap: 12px;\n");
      out.write("    padding: 16px;\n");
      out.write("    border: 2px solid var(--border);\n");
      out.write("    border-radius: var(--radius);\n");
      out.write("    transition: all 0.2s;\n");
      out.write("}\n");
      out.write(".payment-method input[type=\"radio\"]:checked + .payment-method-content {\n");
      out.write("    border-color: var(--primary);\n");
      out.write("    background-color: rgba(46, 125, 50, 0.05);\n");
      out.write("}\n");
      out.write(".payment-icon {\n");
      out.write("    width: 48px;\n");
      out.write("    height: 48px;\n");
      out.write("    border-radius: 8px;\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    justify-content: center;\n");
      out.write("}\n");
      out.write(".btn-block {\n");
      out.write("    width: 100%;\n");
      out.write("}\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
